version: '3'

services:

  redis-master:
    container_name: "redis-master"
    image: redis:6.0-alpine
    command: redis-server /etc/redis.conf
    volumes:
      - "./redis/redis.conf:/etc/redis.conf"
    ports:
      - "6379:6379"
  
  redis-slave1:
    container_name: "redis-slave1"
    image: redis:6.0-alpine
    ports:
      - "6380:6379"
    volumes:
      - "./redis/redis.conf:/etc/redis.conf"
    command: redis-server /etc/redis.conf --slaveof redis-master 6379
  
  redis-slave2:
    container_name: "redis-slave2"
    image: redis:6.0-alpine
    ports:
      - "6381:6379"
    volumes:
      - "./redis/redis.conf:/etc/redis.conf" 
    command: redis-server /etc/redis.conf --slaveof redis-master 6379
  
  redis-sentinel1:
    container_name: 'redis-sentinel1'
    image: redis:6.0-alpine
    ports:
      - "5003:5000"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./sentinel/sentinel.conf:/etc/sentinel.conf"
  
  redis-sentinel2:
    container_name: 'redis-sentinel2'
    image: redis:6.0-alpine
    ports:
      - "5001:5000"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./sentinel/sentinel.conf:/etc/sentinel.conf"
  
  redis-sentinel3:
    container_name: 'redis-sentinel3'
    image: redis:6.0-alpine
    ports:
      - "5002:5000"
    command: redis-server /etc/sentinel.conf --sentinel
    volumes:
      - "./sentinel/sentinel.conf:/etc/sentinel.conf"

